-- 高等数学 (20 questions)
INSERT INTO questions (question_id, stem, options, answer, explanation, question_type, difficulty, knowledge_path, source_type, status, created_at) VALUES ('q_math_001', 'lim(x→0) sin(x)/x 的值为：', '[{"label":"A","content":"0"},{"label":"B","content":"1"},{"label":"C","content":"∞"},{"label":"D","content":"不存在"}]', 'B', '这是重要极限之一，lim(x→0) sin(x)/x = 1。', 'single', 'easy', '高等数学/极限/极限计算', 'seed', 'active', '2026-06-26T12:00:00.000Z');
INSERT INTO questions (question_id, stem, options, answer, explanation, question_type, difficulty, knowledge_path, source_type, status, created_at) VALUES ('q_math_002', 'lim(x→∞) (1 + 1/x)^x 的值为：', '[{"label":"A","content":"1"},{"label":"B","content":"e"},{"label":"C","content":"∞"},{"label":"D","content":"0"}]', 'B', '这是自然常数 e 的定义：lim(x→∞)(1+1/x)^x = e。', 'single', 'medium', '高等数学/极限/极限计算', 'seed', 'active', '2026-06-26T12:00:00.000Z');
INSERT INTO questions (question_id, stem, options, answer, explanation, question_type, difficulty, knowledge_path, source_type, status, created_at) VALUES ('q_math_003', '函数 f(x) = x² 在 x = 2 处是否连续？', '[{"label":"A","content":"连续"},{"label":"B","content":"不连续"},{"label":"C","content":"无法判断"},{"label":"D","content":"仅左连续"}]', 'A', '多项式函数在其定义域内处处连续。', 'single', 'easy', '高等数学/极限/连续性', 'seed', 'active', '2026-06-26T12:00:00.000Z');
INSERT INTO questions (question_id, stem, options, answer, explanation, question_type, difficulty, knowledge_path, source_type, status, created_at) VALUES ('q_math_004', '无穷小量一定是有界变量。', '[{"label":"A","content":"正确"},{"label":"B","content":"错误"}]', 'B', '无穷小量是以0为极限的变量，但不一定有界（如 x→0 时 x·sin(1/x) 是无穷小但振荡）。不过在有限区间内无穷小确实有界，此题考察概念辨析。', 'judge', 'easy', '高等数学/极限/无穷小', 'seed', 'active', '2026-06-26T12:00:00.000Z');
INSERT INTO questions (question_id, stem, options, answer, explanation, question_type, difficulty, knowledge_path, source_type, status, created_at) VALUES ('q_math_005', 'lim(x→0) (e^x - 1) / x 的值为：', '[{"label":"A","content":"0"},{"label":"B","content":"1"},{"label":"C","content":"e"},{"label":"D","content":"∞"}]', 'B', '利用等价无穷小：e^x - 1 ~ x (x→0)，所以极限为1。', 'single', 'hard', '高等数学/极限/极限计算', 'seed', 'active', '2026-06-26T12:00:00.000Z');
INSERT INTO questions (question_id, stem, options, answer, explanation, question_type, difficulty, knowledge_path, source_type, status, created_at) VALUES ('q_math_006', 'f(x) = x³ 的导数 f''(x) 为：', '[{"label":"A","content":"3x²"},{"label":"B","content":"x²"},{"label":"C","content":"3x"},{"label":"D","content":"3x³"}]', 'A', '幂函数求导：(x^n)'' = nx^(n-1)，所以 (x³)'' = 3x²。', 'single', 'easy', '高等数学/导数/导数定义', 'seed', 'active', '2026-06-26T12:00:00.000Z');
INSERT INTO questions (question_id, stem, options, answer, explanation, question_type, difficulty, knowledge_path, source_type, status, created_at) VALUES ('q_math_007', 'f(x) = sin(x)·cos(x) 的导数为：', '[{"label":"A","content":"cos(2x)"},{"label":"B","content":"-sin(2x)"},{"label":"C","content":"sin(2x)"},{"label":"D","content":"-cos(2x)"}]', 'A', 'f(x) = sin(x)cos(x) = ½sin(2x)，f''(x) = cos(2x)。', 'single', 'medium', '高等数学/导数/求导法则', 'seed', 'active', '2026-06-26T12:00:00.000Z');
INSERT INTO questions (question_id, stem, options, answer, explanation, question_type, difficulty, knowledge_path, source_type, status, created_at) VALUES ('q_math_008', 'f(x) = e^(2x) 的导数为：', '[{"label":"A","content":"e^(2x)"},{"label":"B","content":"2e^(2x)"},{"label":"C","content":"2e^x"},{"label":"D","content":"e^x"}]', 'B', '链式法则：(e^(2x))'' = e^(2x)·(2x)'' = 2e^(2x)。', 'single', 'medium', '高等数学/导数/链式法则', 'seed', 'active', '2026-06-26T12:00:00.000Z');
INSERT INTO questions (question_id, stem, options, answer, explanation, question_type, difficulty, knowledge_path, source_type, status, created_at) VALUES ('q_math_009', 'f(x) = ln(x) 的导数为：', '[{"label":"A","content":"1/x"},{"label":"B","content":"x"},{"label":"C","content":"e^x"},{"label":"D","content":"1/(x+1)"}]', 'A', '(ln x)'' = 1/x，这是基本导数公式。', 'single', 'easy', '高等数学/导数/导数定义', 'seed', 'active', '2026-06-26T12:00:00.000Z');
INSERT INTO questions (question_id, stem, options, answer, explanation, question_type, difficulty, knowledge_path, source_type, status, created_at) VALUES ('q_math_010', '函数在某点可导，则在该点一定连续。', '[{"label":"A","content":"正确"},{"label":"B","content":"错误"}]', 'A', '可导必连续，但连续不一定可导（如 y=|x| 在 x=0 处）。', 'judge', 'medium', '高等数学/导数/可微性', 'seed', 'active', '2026-06-26T12:00:00.000Z');
INSERT INTO questions (question_id, stem, options, answer, explanation, question_type, difficulty, knowledge_path, source_type, status, created_at) VALUES ('q_math_011', '∫2x dx 的结果为：', '[{"label":"A","content":"x² + C"},{"label":"B","content":"2x² + C"},{"label":"C","content":"x + C"},{"label":"D","content":"2 + C"}]', 'A', '∫2x dx = 2·(x²/2) + C = x² + C。', 'single', 'easy', '高等数学/积分/不定积分', 'seed', 'active', '2026-06-26T12:00:00.000Z');
INSERT INTO questions (question_id, stem, options, answer, explanation, question_type, difficulty, knowledge_path, source_type, status, created_at) VALUES ('q_math_012', '∫₀¹ x² dx 的值为：', '[{"label":"A","content":"1/2"},{"label":"B","content":"1/3"},{"label":"C","content":"1"},{"label":"D","content":"2/3"}]', 'B', '∫₀¹ x² dx = [x³/3]₀¹ = 1/3 - 0 = 1/3。', 'single', 'medium', '高等数学/积分/定积分', 'seed', 'active', '2026-06-26T12:00:00.000Z');
INSERT INTO questions (question_id, stem, options, answer, explanation, question_type, difficulty, knowledge_path, source_type, status, created_at) VALUES ('q_math_013', '∫cos(3x) dx 的结果为：', '[{"label":"A","content":"sin(3x) + C"},{"label":"B","content":"3sin(3x) + C"},{"label":"C","content":"(1/3)sin(3x) + C"},{"label":"D","content":"-sin(3x) + C"}]', 'C', '∫cos(3x) dx = (1/3)sin(3x) + C，需要除以内部函数的导数。', 'single', 'medium', '高等数学/积分/换元法', 'seed', 'active', '2026-06-26T12:00:00.000Z');
INSERT INTO questions (question_id, stem, options, answer, explanation, question_type, difficulty, knowledge_path, source_type, status, created_at) VALUES ('q_math_014', '∫x·e^x dx 的结果为：', '[{"label":"A","content":"xe^x - e^x + C"},{"label":"B","content":"xe^x + e^x + C"},{"label":"C","content":"e^x + C"},{"label":"D","content":"x·e^x + C"}]', 'A', '分部积分：∫x·e^x dx = x·e^x - ∫e^x dx = xe^x - e^x + C。', 'single', 'hard', '高等数学/积分/分部积分', 'seed', 'active', '2026-06-26T12:00:00.000Z');
INSERT INTO questions (question_id, stem, options, answer, explanation, question_type, difficulty, knowledge_path, source_type, status, created_at) VALUES ('q_math_015', '∫(1/x) dx 的结果为：', '[{"label":"A","content":"ln|x| + C"},{"label":"B","content":"x + C"},{"label":"C","content":"-1/x² + C"},{"label":"D","content":"ln(x²) + C"}]', 'A', '∫(1/x) dx = ln|x| + C，注意绝对值。', 'single', 'easy', '高等数学/积分/不定积分', 'seed', 'active', '2026-06-26T12:00:00.000Z');
INSERT INTO questions (question_id, stem, options, answer, explanation, question_type, difficulty, knowledge_path, source_type, status, created_at) VALUES ('q_math_016', '微分方程 y'' = 2x 的通解为：', '[{"label":"A","content":"y = x² + C"},{"label":"B","content":"y = 2x + C"},{"label":"C","content":"y = x²"},{"label":"D","content":"y = 2x² + C"}]', 'A', '对 y'' = 2x 两边积分得 y = x² + C。', 'single', 'medium', '高等数学/微分方程/一阶', 'seed', 'active', '2026-06-26T12:00:00.000Z');
INSERT INTO questions (question_id, stem, options, answer, explanation, question_type, difficulty, knowledge_path, source_type, status, created_at) VALUES ('q_math_017', '微分方程 y'' = y 的通解为：', '[{"label":"A","content":"y = Ce^x"},{"label":"B","content":"y = e^x + C"},{"label":"C","content":"y = Cx"},{"label":"D","content":"y = ln|x| + C"}]', 'A', '分离变量：dy/y = dx，积分得 ln|y| = x + C₁，即 y = Ce^x。', 'single', 'hard', '高等数学/微分方程/可分离', 'seed', 'active', '2026-06-26T12:00:00.000Z');
INSERT INTO questions (question_id, stem, options, answer, explanation, question_type, difficulty, knowledge_path, source_type, status, created_at) VALUES ('q_math_018', '微分方程 y'' + y = 0 满足 y(0)=1 的特解为：', '[{"label":"A","content":"y = e^(-x)"},{"label":"B","content":"y = e^x"},{"label":"C","content":"y = -e^x"},{"label":"D","content":"y = 1"}]', 'A', 'y'' = -y 的通解为 y = Ce^(-x)，代入 y(0)=1 得 C=1。', 'single', 'medium', '高等数学/微分方程/一阶线性', 'seed', 'active', '2026-06-26T12:00:00.000Z');
INSERT INTO questions (question_id, stem, options, answer, explanation, question_type, difficulty, knowledge_path, source_type, status, created_at) VALUES ('q_math_019', '等比级数 ∑(n=0→∞) r^n 当 |r| < 1 时的和为：', '[{"label":"A","content":"1/(1-r)"},{"label":"B","content":"r/(1-r)"},{"label":"C","content":"1/(1+r)"},{"label":"D","content":"∞"}]', 'A', '等比级数公式：当|r|<1时，∑r^n = 1/(1-r)。', 'single', 'medium', '高等数学/级数/收敛判别', 'seed', 'active', '2026-06-26T12:00:00.000Z');
INSERT INTO questions (question_id, stem, options, answer, explanation, question_type, difficulty, knowledge_path, source_type, status, created_at) VALUES ('q_math_020', '级数 ∑(1/n) (调和级数) 是收敛的。', '[{"label":"A","content":"正确"},{"label":"B","content":"错误"}]', 'B', '调和级数是发散的，这是经典结论。可以用积分判别法证明。', 'judge', 'hard', '高等数学/级数/收敛判别', 'seed', 'active', '2026-06-26T12:00:00.000Z');

-- 微观经济学 (15 questions)
INSERT INTO questions (question_id, stem, options, answer, explanation, question_type, difficulty, knowledge_path, source_type, status, created_at) VALUES ('q_econ_001', '需求价格弹性系数的绝对值大于1时，该商品的需求是：', '[{"label":"A","content":"富有弹性"},{"label":"B","content":"缺乏弹性"},{"label":"C","content":"单位弹性"},{"label":"D","content":"完全无弹性"}]', 'A', '|Ed| > 1 表示需求富有弹性，价格变动引起需求量更大比例的变动。', 'single', 'easy', '微观经济学/需求理论/需求弹性', 'seed', 'active', '2026-06-26T12:00:00.000Z');
INSERT INTO questions (question_id, stem, options, answer, explanation, question_type, difficulty, knowledge_path, source_type, status, created_at) VALUES ('q_econ_002', '某商品价格从10元降到8元，需求量从100增加到120，其需求价格弹性为：', '[{"label":"A","content":"1"},{"label":"B","content":"0.8"},{"label":"C","content":"1.2"},{"label":"D","content":"2"}]', 'A', 'Ed = (ΔQ/Q)/(ΔP/P) = (20/100)/(-2/10) = 0.2/0.2 = 1（取绝对值）。', 'single', 'medium', '微观经济学/需求理论/需求弹性', 'seed', 'active', '2026-06-26T12:00:00.000Z');
INSERT INTO questions (question_id, stem, options, answer, explanation, question_type, difficulty, knowledge_path, source_type, status, created_at) VALUES ('q_econ_003', '消费者剩余是指：', '[{"label":"A","content":"消费者愿意支付的最高价格与实际支付价格之差"},{"label":"B","content":"商品成本与售价之差"},{"label":"C","content":"消费者收入与支出之差"},{"label":"D","content":"供给量与需求量之差"}]', 'A', '消费者剩余 = 愿意支付的最高价格 - 实际支付价格。', 'single', 'easy', '微观经济学/需求理论/消费者剩余', 'seed', 'active', '2026-06-26T12:00:00.000Z');
INSERT INTO questions (question_id, stem, options, answer, explanation, question_type, difficulty, knowledge_path, source_type, status, created_at) VALUES ('q_econ_004', '正常商品的需求曲线是一条：', '[{"label":"A","content":"向右下方倾斜的曲线"},{"label":"B","content":"向右上方倾斜的曲线"},{"label":"C","content":"水平直线"},{"label":"D","content":"垂直直线"}]', 'A', '根据需求定律，价格与需求量呈反向变动，需求曲线向右下方倾斜。', 'single', 'medium', '微观经济学/需求理论/需求曲线', 'seed', 'active', '2026-06-26T12:00:00.000Z');
INSERT INTO questions (question_id, stem, options, answer, explanation, question_type, difficulty, knowledge_path, source_type, status, created_at) VALUES ('q_econ_005', '商品自身价格下降会导致需求曲线右移。', '[{"label":"A","content":"正确"},{"label":"B","content":"错误"}]', 'B', '自身价格变动导致的是需求量的变动（沿曲线移动），而非需求的变动（曲线移动）。需求曲线移动由收入、偏好等其他因素引起。', 'judge', 'easy', '微观经济学/需求理论/需求变动', 'seed', 'active', '2026-06-26T12:00:00.000Z');
INSERT INTO questions (question_id, stem, options, answer, explanation, question_type, difficulty, knowledge_path, source_type, status, created_at) VALUES ('q_econ_006', '供给曲线通常是一条：', '[{"label":"A","content":"向右上方倾斜的曲线"},{"label":"B","content":"向右下方倾斜的曲线"},{"label":"C","content":"水平直线"},{"label":"D","content":"垂直直线"}]', 'A', '根据供给定律，价格越高，供给量越大，供给曲线向右上方倾斜。', 'single', 'easy', '微观经济学/供给理论/供给曲线', 'seed', 'active', '2026-06-26T12:00:00.000Z');
INSERT INTO questions (question_id, stem, options, answer, explanation, question_type, difficulty, knowledge_path, source_type, status, created_at) VALUES ('q_econ_007', '当市场价格高于均衡价格时，市场会出现：', '[{"label":"A","content":"过剩（超额供给）"},{"label":"B","content":"短缺（超额需求）"},{"label":"C","content":"均衡"},{"label":"D","content":"无法确定"}]', 'A', '价格高于均衡时，供给量大于需求量，出现过剩。', 'single', 'medium', '微观经济学/供给理论/均衡价格', 'seed', 'active', '2026-06-26T12:00:00.000Z');
INSERT INTO questions (question_id, stem, options, answer, explanation, question_type, difficulty, knowledge_path, source_type, status, created_at) VALUES ('q_econ_008', '供给价格弹性的大小主要取决于：', '[{"label":"A","content":"生产周期和调整生产难易程度"},{"label":"B","content":"消费者收入水平"},{"label":"C","content":"商品的替代品数量"},{"label":"D","content":"政府税收政策"}]', 'A', '供给弹性主要取决于生产者调整产量的难易程度和时间长短。', 'single', 'medium', '微观经济学/供给理论/弹性', 'seed', 'active', '2026-06-26T12:00:00.000Z');
INSERT INTO questions (question_id, stem, options, answer, explanation, question_type, difficulty, knowledge_path, source_type, status, created_at) VALUES ('q_econ_009', '完全竞争市场中，单个厂商面临的需求曲线是：', '[{"label":"A","content":"水平直线（完全弹性）"},{"label":"B","content":"向右下方倾斜"},{"label":"C","content":"向右上方倾斜"},{"label":"D","content":"垂直线"}]', 'A', '完全竞争厂商是价格接受者，面临的需求曲线是市场价格水平线。', 'single', 'easy', '微观经济学/市场结构/完全竞争', 'seed', 'active', '2026-06-26T12:00:00.000Z');
INSERT INTO questions (question_id, stem, options, answer, explanation, question_type, difficulty, knowledge_path, source_type, status, created_at) VALUES ('q_econ_010', '垄断厂商实现利润最大化的条件是：', '[{"label":"A","content":"MR = MC"},{"label":"B","content":"P = MC"},{"label":"C","content":"AR = AC"},{"label":"D","content":"TR = TC"}]', 'A', '所有厂商利润最大化的一般条件都是 MR = MC。', 'single', 'medium', '微观经济学/市场结构/垄断', 'seed', 'active', '2026-06-26T12:00:00.000Z');
INSERT INTO questions (question_id, stem, options, answer, explanation, question_type, difficulty, knowledge_path, source_type, status, created_at) VALUES ('q_econ_011', '寡头市场的重要特征是厂商之间存在：', '[{"label":"A","content":"相互依存性"},{"label":"B","content":"完全竞争"},{"label":"C","content":"产品差异化"},{"label":"D","content":"自由进出"}]', 'A', '寡头市场中少数几家厂商相互依存，每家的决策都会影响其他厂商。', 'single', 'medium', '微观经济学/市场结构/寡头', 'seed', 'active', '2026-06-26T12:00:00.000Z');
INSERT INTO questions (question_id, stem, options, answer, explanation, question_type, difficulty, knowledge_path, source_type, status, created_at) VALUES ('q_econ_012', '囚徒困境中，纳什均衡的结果是：', '[{"label":"A","content":"双方都坦白"},{"label":"B","content":"双方都抵赖"},{"label":"C","content":"一方坦白一方抵赖"},{"label":"D","content":"没有均衡"}]', 'A', '囚徒困境的纳什均衡是双方都选择坦白（占优策略均衡），尽管双方都抵赖是帕累托最优。', 'single', 'hard', '微观经济学/市场结构/博弈论', 'seed', 'active', '2026-06-26T12:00:00.000Z');
INSERT INTO questions (question_id, stem, options, answer, explanation, question_type, difficulty, knowledge_path, source_type, status, created_at) VALUES ('q_econ_013', '帕累托最优状态是指：', '[{"label":"A","content":"不可能在不损害他人的情况下使某人更好"},{"label":"B","content":"所有人福利相等"},{"label":"C","content":"社会总福利最大"},{"label":"D","content":"资源配置完全均匀"}]', 'A', '帕累托最优是指资源分配的一种理想状态，不可能在不使任何人境况变坏的情况下，使某些人境况变好。', 'single', 'medium', '微观经济学/福利经济学/帕累托', 'seed', 'active', '2026-06-26T12:00:00.000Z');
INSERT INTO questions (question_id, stem, options, answer, explanation, question_type, difficulty, knowledge_path, source_type, status, created_at) VALUES ('q_econ_014', '负外部性的存在会导致市场：', '[{"label":"A","content":"生产过多（过度配置）"},{"label":"B","content":"生产过少"},{"label":"C","content":"达到最优"},{"label":"D","content":"完全失灵"}]', 'A', '负外部性使得私人成本低于社会成本，导致过度生产。', 'single', 'medium', '微观经济学/福利经济学/外部性', 'seed', 'active', '2026-06-26T12:00:00.000Z');
INSERT INTO questions (question_id, stem, options, answer, explanation, question_type, difficulty, knowledge_path, source_type, status, created_at) VALUES ('q_econ_015', '公共品的基本特征是：', '[{"label":"A","content":"非排他性和非竞争性"},{"label":"B","content":"排他性和竞争性"},{"label":"C","content":"排他性和非竞争性"},{"label":"D","content":"非排他性和竞争性"}]', 'A', '纯公共品具有非排他性（无法排除他人使用）和非竞争性（一人使用不影响他人使用）。', 'single', 'easy', '微观经济学/福利经济学/公共品', 'seed', 'active', '2026-06-26T12:00:00.000Z');

-- 英语 (15 questions)
INSERT INTO questions (question_id, stem, options, answer, explanation, question_type, difficulty, knowledge_path, source_type, status, created_at) VALUES ('q_eng_001', 'The word "ubiquitous" most nearly means:', '[{"label":"A","content":"rare"},{"label":"B","content":"everywhere"},{"label":"C","content":"unique"},{"label":"D","content":"obsolete"}]', 'B', 'Ubiquitous means present, appearing, or found everywhere.', 'single', 'easy', '英语/词汇/高频词汇', 'seed', 'active', '2026-06-26T12:00:00.000Z');
INSERT INTO questions (question_id, stem, options, answer, explanation, question_type, difficulty, knowledge_path, source_type, status, created_at) VALUES ('q_eng_002', 'The company decided to _____ the old building and construct a new one.', '[{"label":"A","content":"demolish"},{"label":"B","content":"diminish"},{"label":"C","content":"distinguish"},{"label":"D","content":"distribute"}]', 'A', 'Demolish means to tear down or destroy a building. Diminish = reduce, distinguish = differentiate, distribute = spread.', 'single', 'medium', '英语/词汇/高频词汇', 'seed', 'active', '2026-06-26T12:00:00.000Z');
INSERT INTO questions (question_id, stem, options, answer, explanation, question_type, difficulty, knowledge_path, source_type, status, created_at) VALUES ('q_eng_003', 'The prefix "anti-" means:', '[{"label":"A","content":"against"},{"label":"B","content":"before"},{"label":"C","content":"with"},{"label":"D","content":"after"}]', 'A', 'Anti- means against or opposed to (e.g., antiwar, antibiotic).', 'single', 'medium', '英语/词汇/词根词缀', 'seed', 'active', '2026-06-26T12:00:00.000Z');
INSERT INTO questions (question_id, stem, options, answer, explanation, question_type, difficulty, knowledge_path, source_type, status, created_at) VALUES ('q_eng_004', 'Choose the correct word: "The results were _____ unexpected."', '[{"label":"A","content":"quite"},{"label":"B","content":"quiet"},{"label":"C","content":"quit"},{"label":"D","content":"quote"}]', 'A', 'Quite (相当) is an adverb modifying "unexpected." Quiet = 安静的, quit = 退出, quote = 引用.', 'single', 'hard', '英语/词汇/易混词', 'seed', 'active', '2026-06-26T12:00:00.000Z');
INSERT INTO questions (question_id, stem, options, answer, explanation, question_type, difficulty, knowledge_path, source_type, status, created_at) VALUES ('q_eng_005', '"Pragmatic" most nearly means:', '[{"label":"A","content":"practical"},{"label":"B","content":"theoretical"},{"label":"C","content":"emotional"},{"label":"D","content":"pessimistic"}]', 'A', 'Pragmatic means dealing with things sensibly and realistically.', 'single', 'easy', '英语/词汇/高频词汇', 'seed', 'active', '2026-06-26T12:00:00.000Z');
INSERT INTO questions (question_id, stem, options, answer, explanation, question_type, difficulty, knowledge_path, source_type, status, created_at) VALUES ('q_eng_006', 'She _____ in this company since 2020.', '[{"label":"A","content":"has worked"},{"label":"B","content":"worked"},{"label":"C","content":"works"},{"label":"D","content":"is working"}]', 'A', '"Since 2020" indicates a period from past to present, requiring present perfect tense.', 'single', 'easy', '英语/语法/时态', 'seed', 'active', '2026-06-26T12:00:00.000Z');
INSERT INTO questions (question_id, stem, options, answer, explanation, question_type, difficulty, knowledge_path, source_type, status, created_at) VALUES ('q_eng_007', 'If I _____ you, I would accept the offer.', '[{"label":"A","content":"were"},{"label":"B","content":"am"},{"label":"C","content":"was"},{"label":"D","content":"be"}]', 'A', 'Subjunctive mood uses "were" for all persons in the if-clause.', 'single', 'medium', '英语/语法/虚拟语气', 'seed', 'active', '2026-06-26T12:00:00.000Z');
INSERT INTO questions (question_id, stem, options, answer, explanation, question_type, difficulty, knowledge_path, source_type, status, created_at) VALUES ('q_eng_008', 'The book _____ I bought yesterday is very interesting.', '[{"label":"A","content":"which"},{"label":"B","content":"who"},{"label":"C","content":"where"},{"label":"D","content":"when"}]', 'A', 'Which/that is used for things in relative clauses. "Who" is for people, "where" for places, "when" for time.', 'single', 'medium', '英语/语法/定语从句', 'seed', 'active', '2026-06-26T12:00:00.000Z');
INSERT INTO questions (question_id, stem, options, answer, explanation, question_type, difficulty, knowledge_path, source_type, status, created_at) VALUES ('q_eng_009', 'Not only _____ hard, but he also helps others.', '[{"label":"A","content":"does he work"},{"label":"B","content":"he does work"},{"label":"C","content":"he works"},{"label":"D","content":"works he"}]', 'A', '"Not only" at the beginning of a sentence triggers partial inversion (auxiliary before subject).', 'single', 'hard', '英语/语法/倒装句', 'seed', 'active', '2026-06-26T12:00:00.000Z');
INSERT INTO questions (question_id, stem, options, answer, explanation, question_type, difficulty, knowledge_path, source_type, status, created_at) VALUES ('q_eng_010', 'The report _____ by the team last week.', '[{"label":"A","content":"was completed"},{"label":"B","content":"completed"},{"label":"C","content":"is completed"},{"label":"D","content":"has completed"}]', 'A', '"Last week" indicates past tense, and the report receives the action, so past passive "was completed" is correct.', 'single', 'easy', '英语/语法/被动语态', 'seed', 'active', '2026-06-26T12:00:00.000Z');
INSERT INTO questions (question_id, stem, options, answer, explanation, question_type, difficulty, knowledge_path, source_type, status, created_at) VALUES ('q_eng_011', 'According to the passage: "The rapid development of artificial intelligence has transformed many industries, from healthcare to finance. While AI brings efficiency and innovation, it also raises concerns about job displacement and ethical issues." What is the main idea?', '[{"label":"A","content":"AI has both benefits and concerns"},{"label":"B","content":"AI only brings positive effects"},{"label":"C","content":"AI will replace all human jobs"},{"label":"D","content":"AI is only used in healthcare"}]', 'A', 'The passage presents both sides: efficiency/innovation AND concerns about jobs/ethics.', 'single', 'medium', '英语/阅读/主旨大意', 'seed', 'active', '2026-06-26T12:00:00.000Z');
INSERT INTO questions (question_id, stem, options, answer, explanation, question_type, difficulty, knowledge_path, source_type, status, created_at) VALUES ('q_eng_012', 'In the sentence "The experiment yielded unexpected results," what does "yielded" mean?', '[{"label":"A","content":"produced"},{"label":"B","content":"destroyed"},{"label":"C","content":"delayed"},{"label":"D","content":"predicted"}]', 'A', 'In this context, "yielded" means "produced" or "generated."', 'single', 'medium', '英语/阅读/细节理解', 'seed', 'active', '2026-06-26T12:00:00.000Z');
INSERT INTO questions (question_id, stem, options, answer, explanation, question_type, difficulty, knowledge_path, source_type, status, created_at) VALUES ('q_eng_013', '"Despite the heavy rain, the match continued." This implies that:', '[{"label":"A","content":"The rain did not stop the match"},{"label":"B","content":"The match was cancelled"},{"label":"C","content":"The rain was light"},{"label":"D","content":"The players enjoyed the rain"}]', 'A', '"Despite" indicates contrast — the rain was heavy BUT the match continued anyway.', 'single', 'hard', '英语/阅读/推理判断', 'seed', 'active', '2026-06-26T12:00:00.000Z');
INSERT INTO questions (question_id, stem, options, answer, explanation, question_type, difficulty, knowledge_path, source_type, status, created_at) VALUES ('q_eng_014', '"The government implemented a new policy to mitigate the effects of climate change." "Mitigate" most likely means:', '[{"label":"A","content":"reduce"},{"label":"B","content":"increase"},{"label":"C","content":"ignore"},{"label":"D","content":"study"}]', 'A', 'Mitigate means to make less severe or reduce the impact of something.', 'single', 'easy', '英语/阅读/词义猜测', 'seed', 'active', '2026-06-26T12:00:00.000Z');
INSERT INTO questions (question_id, stem, options, answer, explanation, question_type, difficulty, knowledge_path, source_type, status, created_at) VALUES ('q_eng_015', 'An author who writes "This so-called solution merely addresses the symptoms while ignoring the root cause" has a tone that is:', '[{"label":"A","content":"critical"},{"label":"B","content":"supportive"},{"label":"C","content":"neutral"},{"label":"D","content":"humorous"}]', 'A', '"So-called" and "merely" are dismissive words, indicating a critical tone toward the solution.', 'single', 'medium', '英语/阅读/观点态度', 'seed', 'active', '2026-06-26T12:00:00.000Z');

-- Paper templates
INSERT INTO paper_templates (paper_id, name, question_ids, total_count, suggest_duration, created_at) VALUES ('paper_sprint_001', '高等数学冲刺卷', '["q_math_001","q_math_002","q_math_003","q_math_004","q_math_005","q_math_006","q_math_007","q_math_008","q_math_009","q_math_010","q_math_011","q_math_012","q_math_013","q_math_014","q_math_015","q_math_016","q_math_017","q_math_018","q_math_019","q_math_020"]', 20, 60, '2026-06-26T12:00:00.000Z');
INSERT INTO paper_templates (paper_id, name, question_ids, total_count, suggest_duration, created_at) VALUES ('paper_sprint_002', '微观经济学冲刺卷', '["q_econ_001","q_econ_002","q_econ_003","q_econ_004","q_econ_005","q_econ_006","q_econ_007","q_econ_008","q_econ_009","q_econ_010","q_econ_011","q_econ_012","q_econ_013","q_econ_014","q_econ_015"]', 15, 45, '2026-06-26T12:00:00.000Z');
INSERT INTO paper_templates (paper_id, name, question_ids, total_count, suggest_duration, created_at) VALUES ('paper_sprint_003', '英语冲刺卷', '["q_eng_001","q_eng_002","q_eng_003","q_eng_004","q_eng_005","q_eng_006","q_eng_007","q_eng_008","q_eng_009","q_eng_010","q_eng_011","q_eng_012","q_eng_013","q_eng_014","q_eng_015"]', 15, 45, '2026-06-26T12:00:00.000Z');
